USE "MSIS-603-Project-Winter-2014-SelectStar"
GO

/*Test Data for Customer_Details*/

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY, CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Safeway', '2341 S Winchester Blvd', 'Campbell', 'CA', '95008', 'USA', 'help@safeway.com', '4083646880')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Whole Foods', '1690 S Bascom Ave', 'Campbell', 'CA', '95008', 'USA', 'Customer_Service@wholefoods.com', '4083715000')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Panera Bread', '501 E Hamilton Ave', 'Campbell', 'CA', '95008', 'USA','Procurement@PaneraBread.com', '4083707840')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE) 
VALUES ('Ikes Sandwiches', '2235 The Alameda', 'Santa Clara', 'CA', '95050', 'USA', 'Ike@ilikeikesplace.com', '4082442034')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE) 
VALUES ('Nob Hill Foods', '1602 W Campbell Ave', 'Campbell', 'CA', '95008', 'USA', 'nobhill@raleys.com', '4083796650')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Santa Clara University', '500 El Camino Real', 'Santa Clara', 'CA', 'USA', '95053', 'Dining@scu.edu', '4085544000')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Trader Joes', '635 Coleman Ave', 'San Jose', 'CA', '95110','USA', 'Admin@TraderJoes.com', '4082989731')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Le Boulanger', '20488 Stevens Creek Blvd', 'Cupertino', 'CA', '95014', 'USA', 'service@leboulanger.com', '4084465151')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Freshly Baked Eatery', '152 N 3rd St #101', 'San Jose', 'CA', '95112', 'USA', 'yum@freshbaked.com', '4082989370')
GO

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIP, CUSTOMER_COUNTRY,  CUSTOMER_EMAIL, CUSTOMER_PHONE)
VALUES ('Lucky Supermarket', '2175 Grant Ave', 'Los Altos', 'CA', '94024', 'USA', 'help@luckysupermarkets.com', '6509691326')
GO

/*Enter HISTORICAL_DATA so that historical data isn't empty*/

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (1,'2010-10-14', 3.50)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (4,'2010-11-18', 8.00)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (5,'2011-01-02', 6.75)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (2,'2011-04-28', 4.00)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (1,'2011-04-28', 8.00)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (2,'2011-09-01', 4.00)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (3,'2012-05-30', 6.00)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (4,'2012-10-10', 7.25)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (4,'2013-09-15', 5.25)
GO

INSERT INTO HISTORICAL_PRICE (product_id, date_changed, price)
VALUES (5,'2013-12-31', 5.50)
GO

/* DISCOUNTS table Test Data */

INSERT INTO DISCOUNTS (DISCOUNT_PERCENT, DISCOUNT_DESCRIPTION)
VALUES (0, 'Nil')
GO

INSERT INTO DISCOUNTS (DISCOUNT_PERCENT, DISCOUNT_DESCRIPTION)
VALUES (5, 'Silver')
GO

INSERT INTO DISCOUNTS (DISCOUNT_PERCENT, DISCOUNT_DESCRIPTION)
VALUES (10, 'Gold')
GO

INSERT INTO DISCOUNTS (DISCOUNT_PERCENT, DISCOUNT_DESCRIPTION)
VALUES (15, 'Platinum')
GO


/*INSERTING DATA INTO SUPPLIER_DETAILS*/

INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Mary n Co.','500 El Camino Real','Santa Clara','CA','USA','95053','mary@maryinc.com','408-408-8040')
GO
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Costco','200 Reed Avenue','San Jose','CA','95101','USA','costco@kirkland.com','408-319-9750')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Walmart','601 Lawrence Expressway','Sunnyvale','CA','USA','94090','james@walmart.com', '408-651-2050')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Bay Area Suppliers','320 Castro Street','Mountain View','CA','USA','93053','tim@basuppliers.com','408-539-6235')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Mountain High LLC.','96 Murphy Street','Sunnyvale','CA','USA','94086','mary@maryinc.com','408-498-9900')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Nuts n Spices','229 Basset Street','Fremont','CA','USA','97041','lisa@nnsp.com','408-419-6578')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Amul','353 Market Street','Santa Clara','CA','USA','95052','amul@amul.com','408-887-7878')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Smith Food Distributors','572 N Capitol Street','San Jose','CA','USA','92053','smith@smithfood.com','408-312-2312')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Swanson Grocery','23 Alviso Street','Sunnyvale','CA','USA','94082','swanson@swansongrocery.com','408-990-0909')
GO
 
 
INSERT INTO
SUPPLIER_DETAILS (SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_CITY, SUPPLIER_STATE, SUPPLIER_COUNTRY, SUPPLIER_ZIP, SUPPLIER_EMAIL, SUPPLIER_PHONE)
VALUES ('Brenham Wholesale','26 N Fair Oaks Drive','Fremont','CA','USA','97041','robert@brenham.com','408-546-8013')
GO
 
/* STATUSES Table */

INSERT INTO STATUSES
VALUES ('Open')
GO

INSERT INTO STATUSES
VALUES ('Pending Fulfillment')
GO

INSERT INTO STATUSES
VALUES ('Ready to Ship')
GO

INSERT INTO STATUSES
VALUES ('Fulfilled')
GO

INSERT INTO STATUSES
VALUES ('On Hold')
GO

INSERT INTO STATUSES
VALUES ('Canceled')
GO

INSERT INTO STATUSES
VALUES ('Overdue')
GO

/*INSERTING DATA INTO INGREDIENTS TABLE*/
INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Flour', 'Refined Flour', 50)
GO
 
 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Sugar', 'Granulated Cane Sugar', 65)
GO 

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Confectioners Sugar', 'Caster Sugar ', 40)
GO 

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Eggs', 'Organic Eggs', 25)
GO
 
 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Baking Powder', 'Baking Powder', 15)
GO
 
 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Milk', 'FUll Fat Milk   ', 10)
 GO

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Whipping Cream', ' Sweetend Heavy Whipping Cream', 55)
 GO

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Butter', 'Unsalted Butter', 35)
 GO

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Vanilla', 'Vanilla Bean Extract', 12) 
GO

 INSERT INTO
 INGREDIENTS (INGREDIENT_NAME, INGREDIENT_DESCRIPTION, QTY_AVAILABLE)
 VALUES ('Choco Chips', 'Dark Chocolate Chips', 30) 
GO

/* Add data into PRODUCTS */

INSERT INTO PRODUCTS
VALUES ('Fruit Rainbow Muffins', 'So many fruits each one has a different color.', 5, 0)
GO

INSERT INTO PRODUCTS
VALUES ('Death by Chocolate Cake', 'Every Chocolate in the world. Twice.', 5, 0)
GO

INSERT INTO PRODUCTS
VALUES ('Wowzer Bite Cookies', 'These cookies are so good you will make up words.', 5, 0)
GO

INSERT INTO PRODUCTS
VALUES ('Al Sconepone', 'One scone and the cops will never catch you.', 5, 0)
GO

INSERT INTO PRODUCTS
VALUES ('Grey Brownies', 'Why do we still call them brownies?', 5, 0)
GO


/*INSERTING INTO SUPPLIER_INGREDIENTS TABLE*/
/*Assuming that supplier_quote is per single pound/dozen*/

INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (1,1,.99)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (2,1,1.10)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (8,2,1.15)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (4,2,1.00)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (4,4,4.69)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (7,7,2.45)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (10,7,1.85)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (7,8,4.12)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (10,10,2.98)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (9,10,4.55)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (3,6,2.80)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (7,6,3.20)
GO
 
INSERT INTO
SUPPLIER_INGREDIENTS(SUPPLIER_ID, INGREDIENT_ID, SUPPLIER_QUOTE)
VALUES (6,6,2.9)
GO
 
 
 
/*INSERTING INTO RECIPE TABLE*/
/* FOR FRUIT RAINBOW MUFFINS */
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,1,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,2,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,4,10)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,5,1)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,8,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (1,9,2)
GO
 
/*FOR DEATH BY CHOCOLATE*/
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,1,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,2,6)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,4,11)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,5,1)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,8,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,9,2)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (2,10,1)
GO
 
 
/*FOR WOWZER BITE COOKIES*/
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,1,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,2,7)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,4,12)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,5,2)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,8,10)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (3,7,3)
GO
 
 
/*FOR AL SCONEPONE*/
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (4,4,3)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (4,2,10)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (4,7,10)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (4,5,2)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (4,8,1)
GO
 
 
/*FOR GREY BROWNIES*/
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (5,1,5)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (5,2,7)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (5,6,2)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (5,8,3)
GO
 
INSERT INTO
RECIPES(PRODUCT_ID, INGREDIENT_ID, QTY_NEEDED)
VALUES (5,7,2)
GO
 

/*TEST DATA FOR PURCHASE_ORDERS / PURCHASE_ORDER_ITEMS
1)*/
 
INSERT INTO
PURCHASE_ORDERS(SUPPLIER_ID, DATE_ORDERED,PO_QUOTE,STATUS_ID, DATE_RECEIVED)
VALUES (3,'3-05-2014',280,1,NULL)
GO
 
INSERT INTO
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (1,6,100,280)
GO
 
/*-------------------------------------
2)*/
INSERT INTO
PURCHASE_ORDERS(SUPPLIER_ID, DATE_ORDERED,PO_QUOTE,STATUS_ID, DATE_RECEIVED)
VALUES (4,'02-28-2014',569,1,NULL)
GO
 
INSERT INTO
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (2,2,100,100)
GO
 
INSERT INTO
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (2,4,100,469)
GO
 
/*----------------------------------------------
3)*/
INSERT INTO
PURCHASE_ORDERS(SUPPLIER_ID, DATE_ORDERED,PO_QUOTE,STATUS_ID, DATE_RECEIVED)
VALUES (10,'3-08-2014',185,6,NULL)
GO
 
INSERT INTO
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (3,7,100,185)
GO

--4)
INSERT INTO 
PURCHASE_ORDERS(SUPPLIER_ID, DATE_ORDERED,PO_QUOTE,STATUS_ID, DATE_RECEIVED)
VALUES (1,'3-09-2014',99,6,NULL)

INSERT INTO 
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (4,1,100,99)
GO

--5)
INSERT INTO 
PURCHASE_ORDERS(SUPPLIER_ID, DATE_ORDERED,PO_QUOTE,STATUS_ID, DATE_RECEIVED)
VALUES (7,'01-05-2014',320,5,NULL)
GO

INSERT INTO 
PO_ITEMS( PO_ID,INGREDIENT_ID,QTY_ORDERED,PRICE)
VALUES (5,6,100,320)
GO

/*  ==========================INSERTING SALES_ORDERS DATA=============== */
INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-03-2014', '03-29-2014','1', 375, '1', 356.25)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('2', '03-03-2014', '03-29-2014','1', 350, '1', 332.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('3', '03-03-2014', '03-22-2014','1', 1000, '1', 950)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('4', '03-05-2014', '03-22-2014','1', 1075, '1', 1021.25)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('5', '03-05-2014', '03-22-2014','1', 550, '1', 522.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-05-2014', '03-14-2014','2', 250, '1', 237.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-05-2014', '03-14-2014','3', 350, '1', 332.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-05-2014', '03-10-2014','4', 350, '1', 332.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-07-2014', '03-15-2014','5', 250, '1', 237.5)
GO

INSERT INTO SALES_ORDERS (CUSTOMER_ID, ORDER_DATE, SHIP_DATE, STATUS_ID, GROSS_PRICE, DISCOUNT_ID, NET_PRICE)
VALUES ('1', '03-10-2014', '04-05-2014','6', 350, '1', 332.5)
GO

/*  ==========================INSERTING SALES_ORDER_ITEM DATA=============== */
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('1', '1', 50, 0, 100, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('1', '2', 20, 0, 100, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('1', '3', 40, 0, 200, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('1', '4', 10, 0, 50, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('1', '5', 5, 0, 25, '1')
GO
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('2', '1', 10, 0, 50, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('2', '2', 40, 0, 200,'1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('2', '3', 5, 0, 25, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('2', '4', 10, 0, 50, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('2', '5', 5, 0, 25, '1')
GO
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('3', '1', 100, 0, 500, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('3', '2', 20, 0, 100,'1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('3', '3', 60, 0, 300, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('3', '4', 15, 0, 75, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('3', '5', 5, 0, 25, '1')
GO
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('4', '1', 60, 0, 300,'1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('4', '2', 40, 0, 200, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('4', '3', 100, 0, 500, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('4', '4', 10, 0, 50, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('4', '5', 5, 0, 25, '1')
GO
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('5', '1', 50, 0, 250, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('5', '2', 30, 0, 150, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('5', '3', 15, 0, 75, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('5', '4', 10, 0, 50, '1')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('5', '5', 5, 0, 25, '1')
GO
 
INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('6', '1', 50, 0, 250,'2')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('7', '2', 20, 0, 250, '3')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('7', '1', 50, 0, 100, '3')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('8', '1', 50, 0, 250, '4')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('8', '2', 20, 0, 100, '4')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('9', '1', 50, 0,250, '5')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('9', '2', 20, 0, 100, '5')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('10', '1', 50, 0, 250,'6')
GO

INSERT INTO SALES_ORDER_ITEM (ORDER_ID, PRODUCT_ID, QTY_ORDERED, QTY_MADE, ITEM_PRICE, STATUS_ID)
VALUES ('10', '2', 20, 0, 100, '6')
GO

